$(document).ready(function(){
    $("#bars").click(function(){
      $("#navsmallcontent").show(500);
      $('.cross').show();
    });
    $('#cut').click(function(){
        $('.cross').hide();
        $('.navsmall').hide(500);
    })
});